---
- name: Include OS family specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- ansible.builtin.include_tasks: postgresql_pre.yml
- ansible.builtin.include_tasks: postgresql_install.yml

- block: # Config PostgreSQL
  - ansible.builtin.include_tasks: postgresql_search_config.yml
  - ansible.builtin.include_tasks: postgresql_post.yml
  tags:
    - postgresql-config
